name: APIM APIOPS Extractor
 
on:
  workflow_call:
    inputs:
      source-enviroment:
        type: string
        required: true
 
env:
  apiops_release_version: v6.0.0-alpha.1.0.9
 
jobs:
  extractor:
    runs-on: ubuntu-latest
    environment: ${{ inputs.source-enviroment }}
    steps:
    - uses: actions/checkout@v4
 
    - name: Create a new branch
      run: |
        git checkout -b "extracted-api/run-${{ github.run_number }}-${{ github.run_attempt }}" 

    - name: Runs APIOPS Extractor
      env:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AZURE_RESOURCE_GROUP_NAME: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
        API_MANAGEMENT_SERVICE_NAME: ${{ secrets.API_MANAGEMENT_SERVICE_NAME }}
        API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH: ${{ GITHUB.WORKSPACE }}/apimartifacts
        API_SPECIFICATION_FORMAT: "OpenAPIV3Yaml"
        CONFIGURATION_YAML_PATH:  ${{ GITHUB.WORKSPACE }}/configuration.extractor.yaml
      run: |
        Set-StrictMode -Version Latest
        $ErrorActionPreference = "Stop"
        $VerbosePreference = "Continue"
        $InformationPreference = "Continue"
 
        Write-Information "Setting name variables..."
        $releaseFileName = "extractor-linux-x64.zip"
        $executableFileName = "extractor"
 
        Write-Information "Downloading release..."
        $uri = "https://github.com/Azure/apiops/releases/download/${{ env.apiops_release_version }}/$releaseFileName"
        $downloadFilePath = Join-Path "${{ runner.temp }}" $releaseFileName
        Invoke-WebRequest -Uri "$uri" -OutFile "$downloadFilePath"
 
        Write-Information "Extracting release..."
        $executableFolderPath = Join-Path "${{ runner.temp }}" "extractor"
        Expand-Archive -Path "$downloadFilePath" -DestinationPath "$executableFolderPath"
        $executableFilePath = Join-Path "$executableFolderPath" $executableFileName
 
        Write-Information "Setting file permissions..."
        & chmod +x "$executableFilePath"
        if ($LASTEXITCODE -ne 0) { throw "Setting file permissions failed."}
 
        Write-Information "Running extractor..."
        & "$executableFilePath"
        if ($LASTEXITCODE -ne 0) { throw "Running extractor failed."}
 
        Write-Information "Execution complete."
      shell: pwsh

  # create-pull-request:
  #   runs-on: ubuntu-latest
  #   needs: extractor
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4 

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '16'

  #     - name: Install dependencies
  #       run: npm install
  #       working-directory: ./.github/actions/create-pull-request


  #     - name: Run custom action to create pull request
  #       uses: ./.github/actions/create-pull-request                 
  #       with:
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
  #         branch-name: "extracted-api/run-id-${{ github.run_id }}"
  #         pr-title: "Pull Request for Run ID ${{ github.run_id }}"
  #         pr-body: "This PR was created automatically for run ID ${{ github.run_id }}."
 
    - name: Push the new branch
      run: |
        git add ${{ GITHUB.WORKSPACE }}/apimartifacts/*
        if git diff-index --quiet HEAD --; then
          echo "Não há mudanças a serem extraidas da API."
        else
          git config --global user.name "APIOPS Extractor"
          git config --global user.email "apiops-extractor@noreply.com"
          git commit -m "API artifacts from run #${{ github.run_number }} and attempt #${{ github.run_attempt }}."
          git push --set-upstream origin "extracted-api/run-${{ github.run_number }}-${{ github.run_attempt }}"
          git diff "extracted-api/run-${{ github.run_number }}-${{ github.run_attempt }}^" "extracted-api/run-${{ github.run_number }}-${{ github.run_attempt }}"
        fi

    - name: Publish API Management Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts-from-portal
        path: ${{ GITHUB.WORKSPACE }}/apimartifacts