name: APIM APIOPS Publisher
 
on:
  workflow_call:
    inputs:
      destination-enviroment:
        type: string
        required: true

      release:
        type: string
        required: true
      
    
env:
  APIOPS_RELEASE_VERSION: v6.0.0-alpha.1.0.9

jobs:
  
  publisher:

    environment: ${{ inputs.destination-enviroment }}
    runs-on: ubuntu-latest

    steps:
      
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Get commit_id
      id: get-commit-id
      run: |
         git fetch --tags
         TAG_NAME="${{inputs.release}}"
         OUTPUT_COMMIT_ID=$(git rev-list -n 1 $(git tag --contains $TAG_NAME) || echo "none")             
         echo "COMMIT-ID=$OUTPUT_COMMIT_ID" >> $GITHUB_ENV 
 
    - name: Runs APIOPS Publisher
      env:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AZURE_RESOURCE_GROUP_NAME: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
        API_MANAGEMENT_SERVICE_NAME: ${{ secrets.API_MANAGEMENT_SERVICE_NAME }}
        API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH: ${{ GITHUB.WORKSPACE }}/apimartifacts
        CONFIGURATION_YAML_PATH: ${{ GITHUB.WORKSPACE }}/configuration.${{ inputs.destination-enviroment }}.yaml
        COMMIT_ID: ${{ inputs.release != '' && env.COMMIT-ID || github.sha }}
 
      run: |
    
          set -e
          set -o pipefail

          echo "Setting name variables..."
          releaseFileName="extractor-linux-x64.zip"
          executableFileName="extractor"

          echo "Downloading release..."
          uri="https://github.com/Azure/apiops/releases/download/${{env.APIOPS_RELEASE_VERSION}}/$releaseFileName"
          downloadFilePath="${RUNNER_TEMP}/$releaseFileName"
          curl -L -o "$downloadFilePath" "$uri"

          echo "Extracting release..."
          executableFolderPath="${{runner.temp}}/extractor"
          mkdir -p "$executableFolderPath"
          unzip "$downloadFilePath" -d "$executableFolderPath"
          executableFilePath="$executableFolderPath/$executableFileName"

          echo "Setting file permissions..."
          chmod +x "$executableFilePath"

          echo "Running extractor..."
          "$executableFilePath"

          echo "Execution complete."
   