name: API Mgmt APIOPS Extractor
 
on:
  workflow_dispatch:
    inputs:
      source-enviroment:
        type: string
        required: true
        default: dev
 
permissions:
  contents: write
  pull-requests: write
 
jobs:
  call-build:
    uses: ./apim-apiops-extractor.yaml
    with:
      source-enviroment: ${{ inputs.source-enviroment }}
    secrets: inherit